CREATE TABLE IF NOT EXISTS customer (id BIGINT GENERATED BY DEFAULT AS IDENTITY, first_name varchar(45), last_name varchar(20));

INSERT INTO customer (first_name, last_name) values ('lin chen', 'chris');
