CREATE TABLE IF NOT EXISTS student (id BIGINT GENERATED BY DEFAULT AS IDENTITY, username varchar(45), name varchar(20), age int, balance NUMERIC);

INSERT INTO student (username, name, age, balance) values ('lin chen', 'chris', 12, 1000);
