CREATE TABLE IF NOT EXISTS basement (id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE, capacity BIGINT, availability BIGINT);
CREATE TABLE IF NOT EXISTS garage (id BIGINT GENERATED BY DEFAULT AS IDENTITY, is_available BOOLEAN, license VARCHAR, basement_id BIGINT, FOREIGN KEY (basement_id) REFERENCES basement(id));

INSERT INTO basement (capacity, availability) values (3, 3);
INSERT INTO garage (is_available, basement_id) values (true, 1);
INSERT INTO garage (is_available, basement_id) values (true, 1);
INSERT INTO garage (is_available, basement_id) values (true, 1);

CREATE TABLE IF NOT EXISTS ticket (id BIGINT GENERATED BY DEFAULT AS IDENTITY, license VARCHAR, basement_id BIGINT, garage_id BIGINT, staff_id VARCHAR);

