CREATE TABLE IF NOT EXISTS basement (id BIGINT GENERATED BY DEFAULT AS IDENTITY, capacity BIGINT, available BIGINT);
CREATE TABLE IF NOT EXISTS garage (id BIGINT GENERATED BY DEFAULT AS IDENTITY, is_available BOOLEAN, license CHAR);

INSERT INTO basement (capacity, available) values (3, 3);
INSERT INTO garage (is_available) values (true);
INSERT INTO garage (is_available) values (true);
INSERT INTO garage (is_available) values (true);
